preload = ~/Pictures/arch.png
preload = ~/Pictures/arch2.jpg
preload = ~/Pictures/arch3.png
preload = ~/Pictures/arch4.jpg

wallpaper {
    monitor = eDP-1
    path = ~/Pictures/arch.png
    fit_mode = fill
}
